### ISSUE TITLE
Update/Add branch to demo Authorization code flow w/ PKCE using on-behalf-of

### ISSUE THREAD

**Issue by GFoley83** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#11]
Given implicit grant is generally on the way out and not recommended:
https://oauth.net/2/grant-types/implicit/
https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead

And given there's documentation around using Authorization code flow:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

It would be good to get an example of this approach.

**Comment by derisen** [comment]
@GFoley83 you're right. We will move our samples to MSAL.js 2.x once it is GA, however Angular samples will take a bit longer, since MSAL-Angular is based on MSAL.js 1.x with implicit flow at the moment. Of course, one can also use MSAL.js 2.x directly in an Angular project -we don't have that at the moment but we have a React project using it [here in this branch](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/tree/msal-2x). 

Keep in mind that there's very little difference from the developer's perspective between the usage of msal 1.x (implict flow) vs. msal 2.x (auth code flow).

**Comment by derisen** [comment]
Closing this as no further action to take.
